"""add club songs_per_table

Revision ID: c7f3a9d21e08
Revises: a1c3e6f9b2d4
Create Date: 2026-09-17 21:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f3a9d21e08'
down_revision = 'a1c3e6f9b2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('songs_per_table', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('songs_per_table')

    # ### end Alembic commands ###
