"""add club contact fields and table_count

Revision ID: 051b5b391777
Revises: d5eaf2153273
Create Date: 2026-09-07 17:45:34.413726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051b5b391777'
down_revision = 'd5eaf2153273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('table_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('table_count')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
