"""add vip access_code, vip_requests, favorites

Revision ID: 4482e22defc6
Revises: be030806464b
Create Date: 2026-09-05 20:38:14.151978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4482e22defc6'
down_revision = 'be030806464b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('song_title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_favorites_club_user', ['club_id', 'telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('vip_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['kj_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vip_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vip_requests_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vip_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vip_requests_telegram_user_id'), ['telegram_user_id'], unique=False)

    with op.batch_alter_table('vip_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_vip_clients_access_code'), ['access_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vip_clients_access_code'))
        batch_op.drop_column('access_code')

    with op.batch_alter_table('vip_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vip_requests_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_vip_requests_status'))
        batch_op.drop_index(batch_op.f('ix_vip_requests_club_id'))

    op.drop_table('vip_requests')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_telegram_user_id'))
        batch_op.drop_index('ix_favorites_club_user')
        batch_op.drop_index(batch_op.f('ix_favorites_club_id'))

    op.drop_table('favorites')
    # ### end Alembic commands ###
