"""add guest_accounts display_name

Revision ID: 6a8ea308f62a
Revises: 7898ab232164
Create Date: 2026-09-15 17:33:13.814137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8ea308f62a'
down_revision = '7898ab232164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_accounts', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
