"""add guest_statuses

Revision ID: 7898ab232164
Revises: de302262f96c
Create Date: 2026-09-15 01:46:52.159770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7898ab232164'
down_revision = 'de302262f96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['kj_operators.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'telegram_user_id', name='uq_guest_statuses_club_user')
    )
    with op.batch_alter_table('guest_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_statuses_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_statuses_telegram_user_id'), ['telegram_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_statuses_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_guest_statuses_club_id'))

    op.drop_table('guest_statuses')
    # ### end Alembic commands ###
