"""add admin_users google auth fields, make telegram_user_id nullable

Запрос пользователя 2026-09: "нормальный вход через Google в админку" —
Google становится основным способом входа в Admin App (manage.py
admin-link остаётся запасным, по образцу /kjpanel у KJ), поэтому
telegram_user_id больше не обязателен, а AdminUser получает google_sub
(стабильный id аккаунта, заполняется сам при первом входе) и google_email
(вписывается заранее через manage.py set-admin-google-email). Точная копия
cb6ca8f14754_add_kj_operators_google_auth.py для таблицы admin_users.

Revision ID: a1c3e6f9b2d4
Revises: cb6ca8f14754
Create Date: 2026-09-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c3e6f9b2d4'
down_revision = 'cb6ca8f14754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('telegram_user_id', existing_type=sa.BigInteger(), nullable=True)
        batch_op.create_unique_constraint('uq_admin_users_google_sub', ['google_sub'])
        batch_op.create_unique_constraint('uq_admin_users_google_email', ['google_email'])
        batch_op.create_index(batch_op.f('ix_admin_users_google_sub'), ['google_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_google_email'), ['google_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_google_email'))
        batch_op.drop_index(batch_op.f('ix_admin_users_google_sub'))
        batch_op.drop_constraint('uq_admin_users_google_email', type_='unique')
        batch_op.drop_constraint('uq_admin_users_google_sub', type_='unique')
        batch_op.alter_column('telegram_user_id', existing_type=sa.BigInteger(), nullable=False)
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###
