"""add services, vip_clients, orders.service_id

Revision ID: aa78c392dd3d
Revises: f0790c5c0cd5
Create Date: 2026-09-05 00:36:26.597469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa78c392dd3d'
down_revision = 'f0790c5c0cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_club_id'), ['club_id'], unique=False)

    op.create_table('vip_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cashback_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'telegram_user_id', name='uq_vip_clients_club_user')
    )
    with op.batch_alter_table('vip_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vip_clients_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vip_clients_telegram_user_id'), ['telegram_user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('vip_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vip_clients_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_vip_clients_club_id'))

    op.drop_table('vip_clients')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_club_id'))

    op.drop_table('services')
    # ### end Alembic commands ###
