"""add chat_messages, clubs.chat_enabled

Revision ID: be030806464b
Revises: 11919118934d
Create Date: 2026-09-05 01:51:36.970353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be030806464b'
down_revision = '11919118934d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('from_guest', sa.Boolean(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_chat_messages_club_user', ['club_id', 'telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_telegram_user_id'), ['telegram_user_id'], unique=False)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('chat_enabled')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_telegram_user_id'))
        batch_op.drop_index('ix_chat_messages_club_user')
        batch_op.drop_index(batch_op.f('ix_chat_messages_club_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
