"""add guest_accounts photo_data_url

Revision ID: c4e9f27a1b56
Revises: d8f1a2b4c6e9
Create Date: 2026-10-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e9f27a1b56'
down_revision = 'd8f1a2b4c6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_accounts', schema=None) as batch_op:
        batch_op.drop_column('photo_data_url')

    # ### end Alembic commands ###
