"""add kj_operators google auth fields, make telegram_user_id nullable

Запрос пользователя 2026-09: "доступ KJ Pro определяется Google-аккаунтом
клуба" — Google становится основным способом входа в KJ Panel (Telegram
/kjpanel остаётся запасным), поэтому telegram_user_id больше не обязателен,
а KJOperator получает google_sub (стабильный id аккаунта, заполняется сам
при первом входе) и google_email (вписывает администратор клуба заранее,
см. services/kj_admin_service.assign_kj).

Revision ID: cb6ca8f14754
Revises: 6a8ea308f62a
Create Date: 2026-09-16 00:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6ca8f14754'
down_revision = '6a8ea308f62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kj_operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('telegram_user_id', existing_type=sa.BigInteger(), nullable=True)
        batch_op.create_unique_constraint('uq_kj_operators_google_sub', ['google_sub'])
        batch_op.create_unique_constraint('uq_kj_operators_google_email', ['google_email'])
        batch_op.create_index(batch_op.f('ix_kj_operators_google_sub'), ['google_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_kj_operators_google_email'), ['google_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kj_operators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kj_operators_google_email'))
        batch_op.drop_index(batch_op.f('ix_kj_operators_google_sub'))
        batch_op.drop_constraint('uq_kj_operators_google_email', type_='unique')
        batch_op.drop_constraint('uq_kj_operators_google_sub', type_='unique')
        batch_op.alter_column('telegram_user_id', existing_type=sa.BigInteger(), nullable=False)
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###
