"""add table_groups table_group_members table_join_requests

Revision ID: d5eaf2153273
Revises: f848a23791b7
Create Date: 2026-09-06 20:30:15.584065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5eaf2153273'
down_revision = 'f848a23791b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'table_no', 'guest_id', name='uq_table_group_members_unique')
    )
    with op.batch_alter_table('table_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_group_members_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_table_group_members_lookup', ['club_id', 'table_no'], unique=False)

    op.create_table('table_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('admin_guest_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'table_no', name='uq_table_groups_club_table')
    )
    with op.batch_alter_table('table_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_groups_club_id'), ['club_id'], unique=False)

    op.create_table('table_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_join_requests_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_table_join_requests_lookup', ['club_id', 'table_no', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_join_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_join_requests_status'))
        batch_op.drop_index('ix_table_join_requests_lookup')
        batch_op.drop_index(batch_op.f('ix_table_join_requests_club_id'))

    op.drop_table('table_join_requests')
    with op.batch_alter_table('table_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_groups_club_id'))

    op.drop_table('table_groups')
    with op.batch_alter_table('table_group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_table_group_members_lookup')
        batch_op.drop_index(batch_op.f('ix_table_group_members_club_id'))

    op.drop_table('table_group_members')
    # ### end Alembic commands ###
