"""add club queue_mode

Revision ID: e3a7c159f4d2
Revises: 9f3d7c2a1b6e
Create Date: 2026-09-24 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a7c159f4d2'
down_revision = '9f3d7c2a1b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_mode', sa.String(length=16), nullable=False, server_default='manual'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('queue_mode')

    # ### end Alembic commands ###
