"""baseline: clubs, kj_operators, orders, transactions

Revision ID: f0790c5c0cd5
Revises: 
Create Date: 2026-09-05 00:29:23.678758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0790c5c0cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bridge_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('club_id'),
    sa.UniqueConstraint('bridge_token')
    )
    op.create_table('kj_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kj_operators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kj_operators_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('guest_type', sa.String(length=20), nullable=True),
    sa.Column('song_title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('key', sa.SmallInteger(), nullable=False),
    sa.Column('tempo', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('vdj_item_id', sa.String(length=255), nullable=True),
    sa.Column('vdj_filepath', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('completion_source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('playing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['kj_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_orders_club_status', ['club_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_transactions_club_user', ['club_id', 'telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_telegram_user_id'), ['telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index('ix_transactions_club_user')
        batch_op.drop_index(batch_op.f('ix_transactions_club_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index('ix_orders_club_status')
        batch_op.drop_index(batch_op.f('ix_orders_club_id'))

    op.drop_table('orders')
    with op.batch_alter_table('kj_operators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kj_operators_telegram_user_id'))

    op.drop_table('kj_operators')
    op.drop_table('clubs')
    # ### end Alembic commands ###
