"""add order_change_requests (guest cancel/replace now needs KJ approval)

Revision ID: 9f3d7c2a1b6e
Revises: c7f3a9d21e08
Create Date: 2026-09-20 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3d7c2a1b6e'
down_revision = 'c7f3a9d21e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('new_song_title', sa.String(length=500), nullable=True),
    sa.Column('new_artist', sa.String(length=500), nullable=True),
    sa.Column('new_service_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.club_id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['kj_operators.id'], ),
    sa.ForeignKeyConstraint(['new_service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_change_requests_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_order_change_requests_lookup', ['club_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_change_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_change_requests_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_change_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_order_change_requests_guest_id'))
        batch_op.drop_index(batch_op.f('ix_order_change_requests_order_id'))
        batch_op.drop_index('ix_order_change_requests_lookup')
        batch_op.drop_index(batch_op.f('ix_order_change_requests_club_id'))

    op.drop_table('order_change_requests')
    # ### end Alembic commands ###
